# Testing a workflwo

name: build:test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: |
          required=("NPM_TOKEN" "github_token" "mouse")
          keys=$(jq -n "$secrets" )

          for i in "${required[@]}"
            do
            has=$(jq 'has('\"$i\"')' <<< $keys)
            val=$(jq 'select('\"$i\"')' <<< $keys)
            if [ $has == true ]; then
              echo "$i is present: value: $val"            
            fi
          done
        name: Verify required parameters
        env:
          secrets: ${{ toJSON(secrets) }}
          vars: ${{ toJSON(vars) }}

      - run: |
          ok_title="Package Published!"
          ok_msg_1="Publish was OK."

          echo "::notice title=${ok_title}::${ok_msg_1}"
        name: Success Message
