# From https://docs.npmjs.com/generating-provenance-statements
# `$ npm publish` with established provenance 
# 
# Required Parameters
# - On environment: `CI`
#   - Secret: `NPM_TOKEN`: An npm access token with read/write permissions

name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: |
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "::error title="Missing req. secret: 'NPM_TOKEN'"
          fi
          echo "::error title="Missing req. secret: 'NPM_TOKEN'"
          exit 1
        if: env.NPM_TOKEN = null
        name: Verify parameters
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
