# Testing a workflwo

name: build:test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: |
          err_title="Missing parameters"
          err_msg_1="Expected: NPM_TOKEN=npm_xxx "
          err_msg_2="Expected: to be found on Environment: CI."

          tip_title="Setting secrets/variables"
          tip_msg_1="Visit: Repository Settings > Secrets/Variables > Actions."
          tip_msg_2="environment: CI must exist, containing above secrets/vars." 

          echo "::error title=${err_title}::${err_msg_1}. ${err_msg_1}."
          echo "::notice title=${tip_title}::${tip_msg_1}. ${tip_msg_2}."
          exit 1
        if: ${{ !startsWith(secrets.NPM_TOKEN, 'npm') }}
        name: Verify required parameters

      - run: |
          ok_title="Package Published!"
          ok_msg_1="Publish was OK."

          echo "::notice title=${ok_title}::${ok_msg_1}"

        if: fromJSON(steps.getsize.outputs.size) <= fromJSON(env.MAX_BYTES)
        name: Success Message
