# Matches package version to release version then commits the change.
# Publishes to `npm` with build provenance.

name: npm publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Match package to release version
        run: |
          # i.e: "v1.2.3" => "1.2.3"
          version=$(echo "$TAG" | sed 's/[^0-9.]*//g')

          npm pkg set version=$version
        env: 
          TAG: ${{ github.event.release.tag_name }}

      - name: Commit version bump
        run: |
          git config --global user.name 'CI release:publish'
          git config --global user.email 'support@github.com'
          git commit -am "build: bump package version to $TAG"
          git push origin HEAD:main
        env: 
          TAG: ${{ github.event.release.tag_name }}

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
