name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [22.9, latest]

    steps:
    
    - name: Checkout branch ${{ github.head_ref || github.ref_name }} 
      uses: actions/checkout@v4

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Tests on CI should install unpinned dependencies (weird rule)
    # From: OSSF: Package Manager Best Practices
    # Read: https://github.com/ossf/package-manager-best-practices/blob/f51988aee8a9a1ab0436bbba61c1e94d7270683a/published/npm.md?plain=1#L297
    - name: Install unpinned dependencies
      run: npm install --no-package-lock
      
    - name: Run tests
      run: node --run test
      env:
        NODE_ENV: test
