# Tests for package dependencies
# 
# Shows error message, & exit 1 if a limit of 
# dependencies or devDependencies is exceeded

name: test:deps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [latest]
    env:
      # Settings
      # dependencies
      MAX_DEPS: 0
      #devDependencies
      MAX_D_DEPS: 0
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # output count of dependencies & devDependencies
    # as 'depsNo' and 'ddepsNo' on both `output` and `env`
    # 
    # computed by counting the number of `:` occurrences
    # in their respective package.json fields
    - run: | 
        depsCount=$(npm pkg get dependencies | tr -cd ':' | wc -c);
        echo "depsCount=$depsCount" >> "$GITHUB_OUTPUT";
        echo "depsCount=$depsCount" >> "$GITHUB_ENV";
      name: get dependencies and devDependencies count
      id: package

    # if depsNo < MAX_DEPS, err message & exit 1
    - run: |
        t="too many dependencies" && \
        e="Lists ${depsCount} dependencies, max limit is: ${MAX_DEPS}." && \
        echo "::error title=${t}::${e}." && exit 1

      if: fromJSON(steps.package.outputs.depsCount) > fromJSON(env.MAX_DEPS)
      name: Too Many Dependencies Error

    # else print OK message
    - run: |
        t="dependency count OK" && \
        a="Lists ${depsCount} dependencies, limit is: ${MAX_DEPS}" \
        b="Lists ${ddepsCount} devDependencies, limit is: ${MAX_DDEPS}" \

        echo "::notice title=${t}::${a}." && echo "::notice title=${t}::${b}."

      name: Dependency Count OK
