# Tests for package dependencies
# 
# Shows error message, & exit 1 if a limit of 
# dependencies or devDependencies is exceeded

name: test:deps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [latest]
    env:
      # Settings
      # dependencies
      MAX__DEPS: 0
      #devDependencies
      MAX_D_DEPS: 0
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # output count of dependencies & devDependencies
    # as 'deps_no' and 'ddeps_no' on both `output` and `env`
    # 
    # computed by counting the number of `:` occurrences
    # in their respective package.json fields
    - run: | 
        deps_no=$(npm pkg get dependencies | tr -cd ':' | wc -c);
        ddeps_no=$(npm pkg get devDependencies | tr -cd ':' | wc -c);

        "deps_no=${deps_no}" >> "$GITHUB_OUTPUT" &&
        "ddeps_no=${ddeps_no}" >> "$GITHUB_OUTPUT" &&

        "deps_no=${deps_no}" >> "$GITHUB_ENV" &&
        "ddeps_no=${ddeps_no}" >> "$GITHUB_ENV"
      name: get dependencies and devDependencies count
      id: packageJSON

    # if deps_no < MAX_DEPS, err message & exit 1
    - run: |
        t="too many dependencies" && \
        e="Lists ${deps_no} dependencies, max limit is: ${MAX_DEPS}." && \
        echo "::error title=${t}::${e}." && exit 1

      if: fromJSON(steps.packageJSON.outputs.deps_no) > 0
      name: Too Many Dependencies Error

    # if ddeps_no < MAX_D_DEPS, err message & exit 1
    - run: |
        t="too many devDependencies" && \
        e="Lists ${ddeps_no} dependencies, limit is: ${MAX_DDEPS}" \

        echo "::error title=${t}::${e}." && exit 1
      if: fromJSON(steps.packageJSON.outputs.ddeps_no) > 0
      name: Too Many devDependencies Error

    # else print OK message
    - run: |
        t="dependency count OK" && \
        a="Lists ${deps_no} dependencies, limit is: ${MAX_DEPS}" \
        b="Lists ${ddeps_no} devDependencies, limit is: ${MAX_DDEPS}" \

        echo "::notice title=${t}::${a}." && echo "::notice title=${t}::${b}."

      name: Dependency Count OK
