name: test:size

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [latest]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i -D webpack-cli
    # Bundle & minify src/index.js 
    - run: npx webpack --mode production --output-library-type module --experiments-output-module
    # compress it
    - run: gzip dist/main.mjs
    # Get gzip size, compare > BYTE_LIMIT, print message, exit 1 if yes
    - run: >
        size=$(wc -c < dist/main.mjs.gz | tr -d '[:space:]');\ 
          test "$size" -lt "$BYTE_LIMIT" &&\
          echo "size ${size} bytes within ${BYTE_LIMIT} bytes limit" ||\ 
          (echo "size ${size} bytes > ${BYTE_LIMIT} bytes limit" >&2 && exit 1);  
      env:
        BYTE_LIMIT: 999
    # Cleanup
    - run: npm r -D webpack-cli; rm -rf dist/
